// Name: Kavindu Lakmal
// Date: 21/10/2022

/* 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Implementation:

Each letter has a respective ASCII int value,

calculating the sum of the int converted ascii value of each character of the two strings,

and getting their difference, will return a single int value,

which when converted back to a character, will be the added letter of the string t.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        int sInt = 0, tInt = 0;
        for(int i = 0; i < s.length(); i++)
            sInt += s.charAt(i);
        for(int i = 0; i < t.length(); i++)
            tInt += t.charAt(i);
        return  (char) (tInt - sInt);
    }
}